# Generated by Django 5.1.3 on 2024-12-29 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaLuigui', '0002_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Products',
        ),
    ]
